#include "arduino_secrets.h"
// WiFi - Version: Latest 
#include <WiFiClient.h>
#include "ThingSpeak.h"

// Servo - Version: Latest 
#include <Servo.h>
// #include<Servo_ESP32.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/903fcf12-140a-4791-947b-53ee7ceee2b8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led;
  int servo;
  bool buzzer;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


#define LED 15
#define buzz 2
#define servo_pin 4

#define myChannelNumber 1666913
#define myWriteAPIKey "E0SK9ZEWEWK0JEB0"
Servo s;

WiFiClient client;

// int current, previous=0;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  s.attach(servo_pin);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(LED, OUTPUT);
  pinMode(buzz, OUTPUT);
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  ThingSpeak.begin(client);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  // current=millis();
  // s.write(0);
  // if(current-previous>=2000)
  // {
  //   s.write(90);
  //   previous=current;
  // }
  int x = ThingSpeak.writeFields(myChannelNumber, myWriteAPIKey);
  ThingSpeak.setField(1, led);
  ThingSpeak.setField(2, buzzer);
  // ThingSpeak.setField(3, stepM);

    
  //ThingSpeak.setField(2,led1);
  if(x == 200){
    Serial.println("Channel update successful.");
  }
  else{
    Serial.println("Problem updating channel. HTTP error code " + String(x));
  }
}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  if(led==1)
  {
    digitalWrite(LED, HIGH);
  }
  else
  {
    digitalWrite(LED, LOW);
  }
  // Add your code here to act upon Led change
}

void onBuzzerChange()  {
  // Add your code here to act upon Buzzer change
  if(buzzer==1)
  {
    digitalWrite(buzz, HIGH);
  }
  else
  {
    digitalWrite(buzz, LOW);
  }
}

/*
  Since Servo is READ_WRITE variable, onServoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onServoChange()  {
  // Add your code here to act upon Servo change
  // Serial.println(servo);
  s.write(servo);
  delay(100);
  // // delay(1000);
}